### ISSUE TITLE
blibrary.h is incorrect

### ISSUE THREAD

**Issue by McTwist** [hatf0/blbrowser2#1]
The file blibrary.h is not valid as the name and description is pointers, but the real type is arrays. Recommended to fix it, even if leaks doesn't occur.

**Comment by hatf0** [comment]
Yeah, I know. I changed them to pointers for better compatibility. I'll switch them back here later.

**Comment by McTwist** [comment]
Well, the address is coupled to the allocated space, so it's not lost. But it's not a pointer either, so reading it will result in pointer garbage. That is, it's totally invalid.

So for short: pointers are not arrays and arrays are not pointers, but arrays may convert to pointers, but not pointers to arrays.
